// Package catalog renders an `internal/inspect.Output` into the
// human-readable `docs/TOOLS.md` that backs `make catalog` (FR11).
//
// The renderer is deterministic and idempotent: it sorts every list by its
// identity key and reads no environment-derived state (no timestamps, no
// random ids), so running `make catalog` twice produces a byte-identical
// file. The fail-on-drift Makefile pattern depends on this guarantee.
package catalog

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/andygeiss/mcp/internal/inspect"
	"github.com/andygeiss/mcp/internal/schema"
	"github.com/andygeiss/mcp/internal/tools"
)

// Render writes a Markdown catalog of every tool in out to w.
func Render(out inspect.Output, w io.Writer) error {
	rendered := append([]tools.Tool{}, out.Tools...)
	sort.SliceStable(rendered, func(i, j int) bool { return rendered[i].Name < rendered[j].Name })

	if _, err := fmt.Fprintln(w, "# Tools Catalog"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, ""); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "> Generated by `make catalog` from the reflection-derived registry. Do not edit by hand."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, ""); err != nil {
		return err
	}

	if err := renderSummary(w, rendered); err != nil {
		return err
	}
	if err := renderDetails(w, rendered); err != nil {
		return err
	}
	return nil
}

func renderSummary(w io.Writer, ts []tools.Tool) error {
	if _, err := fmt.Fprintln(w, "| Name | Description | Required input | Output |"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "|---|---|---|---|"); err != nil {
		return err
	}
	for _, t := range ts {
		row := fmt.Sprintf("| `%s` | %s | %s | %s |",
			escapeMarkdownInline(t.Name),
			escapeMarkdownInline(t.Description),
			requiredInputsSummary(t.InputSchema),
			outputSummary(t.OutputSchema),
		)
		if _, err := fmt.Fprintln(w, row); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintln(w, ""); err != nil {
		return err
	}
	return nil
}

func renderDetails(w io.Writer, ts []tools.Tool) error {
	if _, err := fmt.Fprintln(w, "## Detail"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, ""); err != nil {
		return err
	}
	for _, t := range ts {
		if err := renderOneTool(w, t); err != nil {
			return err
		}
	}
	return nil
}

func renderOneTool(w io.Writer, t tools.Tool) error {
	if _, err := fmt.Fprintf(w, "### `%s`\n\n", escapeMarkdownInline(t.Name)); err != nil {
		return err
	}
	if t.Description != "" {
		if _, err := fmt.Fprintf(w, "%s\n\n", escapeMarkdownInline(t.Description)); err != nil {
			return err
		}
	}
	if err := renderSchemaSection(w, "**Input schema:**", t.InputSchema.Properties, t.InputSchema.Required); err != nil {
		return err
	}
	if t.OutputSchema != nil {
		if _, err := fmt.Fprintln(w, ""); err != nil {
			return err
		}
		if err := renderSchemaSection(w, "**Output schema:**", t.OutputSchema.Properties, t.OutputSchema.Required); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintln(w, ""); err != nil {
		return err
	}
	return nil
}

func renderSchemaSection(w io.Writer, header string, props map[string]schema.Property, required []string) error {
	if _, err := fmt.Fprintln(w, header); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, ""); err != nil {
		return err
	}
	return renderPropertyTable(w, props, required)
}

func renderPropertyTable(w io.Writer, props map[string]schema.Property, required []string) error {
	if len(props) == 0 {
		_, err := fmt.Fprintln(w, "_(no fields)_")
		return err
	}
	if _, err := fmt.Fprintln(w, "| Field | Type | Required | Description |"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "|---|---|---|---|"); err != nil {
		return err
	}

	requiredSet := make(map[string]bool, len(required))
	for _, r := range required {
		requiredSet[r] = true
	}
	names := make([]string, 0, len(props))
	for n := range props {
		names = append(names, n)
	}
	sort.Strings(names)

	for _, name := range names {
		p := props[name]
		req := "no"
		if requiredSet[name] {
			req = "yes"
		}
		row := fmt.Sprintf("| `%s` | %s | %s | %s |",
			escapeMarkdownInline(name),
			describeType(p),
			req,
			escapeMarkdownInline(p.Description),
		)
		if _, err := fmt.Fprintln(w, row); err != nil {
			return err
		}
	}
	return nil
}

// requiredInputsSummary renders a one-line summary of the required input
// fields for the top-summary table. Returns "_(none)_" when no fields are
// required.
func requiredInputsSummary(s schema.InputSchema) string {
	if len(s.Required) == 0 {
		return "_(none)_"
	}
	required := append([]string{}, s.Required...)
	sort.Strings(required)
	parts := make([]string, 0, len(required))
	for _, name := range required {
		p := s.Properties[name]
		parts = append(parts, fmt.Sprintf("`%s` (%s)", escapeMarkdownInline(name), describeType(p)))
	}
	return strings.Join(parts, ", ")
}

// outputSummary renders a one-line summary of the output schema. Returns
// `object` when an output schema is present (even with no fields, the wire
// shape is `{"type":"object"}`); returns "_(none)_" when no schema is set.
func outputSummary(s *schema.OutputSchema) string {
	if s == nil {
		return "_(none)_"
	}
	if len(s.Properties) == 0 {
		return "`object` (empty)"
	}
	names := make([]string, 0, len(s.Properties))
	for n := range s.Properties {
		names = append(names, n)
	}
	sort.Strings(names)
	parts := make([]string, 0, len(names))
	for _, name := range names {
		p := s.Properties[name]
		parts = append(parts, fmt.Sprintf("`%s` (%s)", escapeMarkdownInline(name), describeType(p)))
	}
	return strings.Join(parts, ", ")
}

// describeType returns a short type token for a Property: primitives render
// as their JSON Schema type ("string", "integer"); arrays as "array<elem>";
// objects as "object".
func describeType(p schema.Property) string {
	t := p.Type
	if t == "" {
		return "any"
	}
	if t == schema.TypeArray && p.Items != nil {
		return fmt.Sprintf("array<%s>", describeType(*p.Items))
	}
	return t
}

// escapeMarkdownInline replaces Markdown control characters that would break
// table rendering or inline formatting. The set is intentionally narrow:
// only the characters that cause table/inline collisions, since over-
// escaping makes the catalog harder to read.
func escapeMarkdownInline(s string) string {
	if s == "" {
		return ""
	}
	r := strings.NewReplacer(
		"|", `\|`,
		"\n", " ",
	)
	return r.Replace(s)
}
