// Package main is the spec-coverage renderer: it iterates the in-memory
// protocol.Clauses registry and prints a tab-separated audit table to
// stdout. Bootstrap registrations live in _test.go init() blocks (so they
// fail to compile if a referenced test is renamed), which means this
// `go run` entry point sees an empty registry. The committed audit
// artifact at docs/spec-coverage.txt is regenerated by the
// Test_RenderSpecCoverage_Should_WriteCommittedReport test, invoked via
// `make spec-coverage`. This binary exists so the renderer's import path
// and signature stay compile-checked under plain `go build ./...`.
package main

import (
	"fmt"
	"os"

	"github.com/andygeiss/mcp/internal/protocol"
)

func main() {
	if err := protocol.Render(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}
